### ISSUE TITLE
Link to scamsite in MacWire section

### ISSUE THREAD

**Issue by cptwunderlich** [di-in-scala/di-in-scala.github.io-sources#11]
The section "Using MacWire for wiring" contains a link to scalamacros.org - it seems like this site was taken over by some link-farm or i don't know what kind of scammy thing.
Maybe it would be better to replace it with a link to the official docs, e.g., https://docs.scala-lang.org/scala3/guides/macros/macros.html

**Comment by adamw** [comment]
Definitely! Would you maybe have the opportunity to create a PR?

**Comment by adamw** [comment]
Thanks :) I'll have to remind myself how this site was built, and hopefully deploy in the evening :)

**Comment by adamw** [comment]
Done :)
